### ISSUE TITLE
URL not available for kubescrape desktop application

### ISSUE THREAD

**Issue by Sayali1638** [oslabs-beta/KubeScrape#56]
Trying to download the kubescrape desktop application. Cannot access the url.
![image](https://user-images.githubusercontent.com/66510021/144440658-08dd7cf7-b032-46c3-8218-bc6dacbade65.png)

How can i download the application

**Comment by ntgv93** [comment]
Hi @Sayali1638,

The tool can be downloaded in the releases here: https://github.com/oslabs-beta/KubeScrape/releases

It appears that the URL in the readme was broken - it has since been updated. Thanks for bringing it to our attention!

Cheers,
Vince
